[theme]
primaryColor = "#28f0ff"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "monospace"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = true
toolbarMode = "minimal"
